name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap hari pukul 00:00 UTC
  workflow_dispatch:

jobs:
  generate-pacman-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
